version: "3.7"
services:

  project-setup:
    image: debian:buster
    volumes:
      - ./odoo:/odoo/
    user: root
    command: chmod 777 -R /odoo/

  odoo:
    image: odoo:13.0
    depends_on:
      - db
      - project-setup
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/web:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons

  api-poc:
    build: ./api-poc
    depends_on:
      - odoo
    volumes:
      - ./api-poc/:/usr/src/app
    environment:
      FLASK_APP: main.py
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0

  db:
    image: postgres:10.14-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      TZ: America/Recife
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080